apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hfao.fullname" . }}-ingest
  labels:
    {{- include "hfao.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  replicas: {{ .Values.ingest.replicaCount }}
  selector:
    matchLabels:
      {{- include "hfao.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingest
  template:
    metadata:
      {{- with .Values.ingest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hfao.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingest
    spec:
      serviceAccountName: {{ include "hfao.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ingest
          image: "{{ .Values.imageIngest.repository }}:{{ include "hfao.ingestImageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          env:
            - name: HFAO_INGEST_HOST
              value: "0.0.0.0"
            - name: HFAO_INGEST_PORT
              value: "4318"
            {{- include "hfao.envCommon" . | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: otlp-http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: otlp-http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.ingest.resources | nindent 12 }}
      {{- with .Values.ingest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
